# Generated by Django 3.2 on 2024-03-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_book_purchasedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='ex@gmail.com', max_length=254),
        ),
    ]
