# Generated by Django 4.2.11 on 2024-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_book_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
